[project]
name = "canvod-store"
version = "0.1.0"
description = "Icechunk and Zarr storage backends"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[tool.ty]
extend-exclude = [
    "**/docs/*.ipynb",
]

[tool.uv.build-backend]
module-name = "canvod.store"
