[project]
name = "canvod-readers"
version = "0.1.0"
description = "GNSS data format readers"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "canvod.readers"
