[project]
name = "canvodpy"
version = "0.1.0"
description = "Umbrella package for canVOD ecosystem"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[tool.ty]
extend-exclude = [
    "**/docs/*.ipynb",
]
