[project]
name = "canvod-grids"
version = "0.1.0"
description = "HEALPix and hemispheric grid operations"
authors = [
    {name = "Nicolas FranÃ§ois Bader", email = "nicolas.bader@geo.tuwien.ac.at"},
]
maintainers = [
    {name = "Climate and Environmental Remote Sensing (CLIMERS)", email = "nicolas.bader@geo.tuwien.ac.at"},
]
requires-python = ">=3.13"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "numpy>=1.26.0",
]

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[tool.ty]
extend-exclude = [
    "**/docs/*.ipynb",
]

[tool.uv.build-backend]
module-name = "canvod.grids"
