[project]
name = "canvod-vod"
version = "0.1.0"
description = "Vegetation Optical Depth calculations"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
extend-exclude = [
    "**/docs/*.ipynb",
]

[tool.uv.build-backend]
module-name = "canvod.vod"
