name: Platform Tests ğŸğŸ§ğŸ

on: [push, pull_request]

jobs:
    build:
        name: Tests â€¢ ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: ubuntu-latest
                      python-version: '3.13'
                      name: 'ğŸ 3.13 â€¢ ğŸ§ Ubuntu'
                    - os: ubuntu-latest
                      python-version: '3.14'
                      name: 'ğŸ 3.14 â€¢ ğŸ§ Ubuntu'
                    - os: windows-latest # Note: 'aux' package may have issues
                      python-version: '3.13'
                      name: "ğŸ 3.13 â€¢ ğŸªŸ Windows"
                    - os: windows-latest
                      python-version: '3.14'
                      name: "ğŸ 3.14 â€¢ ğŸªŸ Windows"
                    - os: macos-latest
                      python-version: '3.13'
                      name: 'ğŸ 3.13 â€¢ ğŸ macOS'
                    - os: macos-latest
                      python-version: '3.14'
                      name: 'ğŸ 3.14 â€¢ ğŸ macOS'

        defaults:
            run:
                shell: bash

        steps:
            - uses: actions/checkout@v4
            - name: Install uv and set the python version
              uses: astral-sh/setup-uv@v6
              with:
                  python-version: ${{ matrix.python-version }}
                  enable-cache: true
            - name: Set up Python
              run: uv python install
            - name: Install just
              uses: ./.github/actions/setup-just
            - name: Install the Project
              run: uv sync --locked --dev
            - name: Run Tests
              run: just test-all-packages
